# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

target 'StudySSE' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift', '~> 6.5.0'
  pod 'RxCocoa', '~> 6.5.0'
  pod 'SnapKit', '~> 5.0.1'
  pod 'Moya', '~> 15.0.0'
  # Pods for StudySSE

end
